runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'axciona_strapi'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'Licassss5151'
  INSTANCE_CONNECTION_NAME: 'axcionafront:europe-southwest1:axciona-db'

beta_settings:
  cloud_sql_instances: 'axcionafront:europe-southwest1:axciona-db'
