runtime: nodejs16

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'axciona_strapi'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'Licassss5151'
  INSTANCE_CONNECTION_NAME: 'avid-infinity-370500:us-central1:axciona-mysql'
  DB_HOST: '34.66.185.87'

beta_settings:
  cloud_sql_instances: 'avid-infinity-370500:us-central1:axciona-mysql'
